version: '3'

services:
  nodejs:
    build: ./
    image: piantkoski/ubuntu-sshd:latest
    volumes:
      - ./workspace:/workspace
    ports:
      - "22:22"
      - "3090:3090"
    networks:
      - crud-node
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - crud-node
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "80"
    networks:
      - crud-node
    depends_on:
      - db

networks:
  crud-node:
    driver: bridge