version: '3'

services:
  nodejs:
    image: piantkoski/app-node-dockerizado:latest
    build: .
    ports:
      - "3090:3090"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./workspace/postgres:/var/lib/postgresql/data
  

